version: '3.8'

services:
  backend:
    image: fastapi-backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    image: react-vite-frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:8000/produits/

networks:
  app-network:
    driver: bridge
