version: '3.8'

services:
  backend:
    image: yassinekassem/nike-shop-backend:latest
    container_name: nike-shop-backend
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    ports:
      - "8000:8000"

  frontend:
    image: yassinekassem/nike-shop-frontend:latest
    container_name: nike-shop-frontend
    ports:
      - "5173:5173"
