version: "1.0"

# Qodana settings for FastAPI (Python)
inspection:
  # Enable or disable specific inspections
  include:
    - Python | PEP8 Coding Style | *  # Enforce PEP8 style guidelines
    - Python | Code Complexity | *    # Check for cyclomatic complexity
    - Python | Common Bugs | *        # Identify common Python bugs

  exclude:
    - Python | Type Hints | *         # Disable Type Hints inspection if not using type hints extensively

# Paths and files to analyze or ignore
fileMasks:
  include:
    - "**/*.py"                       # Include all Python files
  exclude:
    - "**/tests/**"                   # Optionally exclude tests if needed
    - "**/__pycache__/**"             # Exclude compiled Python cache

output:
  report: "qodana-report-python"      # Specify output directory for Python report

# Additional settings
settings:
  failThreshold: 5                    # Pipeline fails if more than 5 issues are found
  maxComplexity: 10                   # Set max cyclomatic complexity allowed
